from app.config import (
    CONFIDENCE_THRESHOLD,
    FILENAME_BOOST_FACTOR,
    FUZZY_CONFIDENCE_CAP,
    FUZZY_CORRECTION_ENABLED,
    FUZZY_MAX_CANDIDATES,
    HEADING_BOOST_FACTOR,
    HEADING_OVERLAP_THRESHOLD,
    KNOWLEDGE_DIR,
    MAX_RESULTS,
    MAX_SYNONYMS_PER_TOKEN,
    REFERENCE_PATH_BOOST,
    SCORE_SCALE,
    WATCHER_DEBOUNCE_MS,
)


def test_config_defaults():
    assert KNOWLEDGE_DIR == "knowledge/"
    assert CONFIDENCE_THRESHOLD == 0.1
    assert SCORE_SCALE == 25.0
    assert MAX_RESULTS == 3
    assert WATCHER_DEBOUNCE_MS == 500
    assert MAX_SYNONYMS_PER_TOKEN == 2
    assert HEADING_BOOST_FACTOR == 2.0
    assert HEADING_OVERLAP_THRESHOLD == 0.5
    assert FILENAME_BOOST_FACTOR == 1.4
    assert REFERENCE_PATH_BOOST == 1.2
    assert FUZZY_CORRECTION_ENABLED is True
    assert FUZZY_MAX_CANDIDATES == 2
    assert FUZZY_CONFIDENCE_CAP == 0.6
